
### GET v2/v3/index
GET http://127.0.0.1:8089/demo/v2/v3/index?name=zhangsan


### GET v1/index
GET http://127.0.0.1:8089/demo/v1/index?name=wangwu

### GET user by id
GET http://127.0.0.1:8089/demo/v1/users/1